name: Test

env:
  CI: true
  DEBUG: pw:api

on:
  push:

jobs:
  run:
    strategy:
      matrix:
        node: ['18']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{secrets.GITHUB_TOKEN}}
      - name: npm ci
        run: npm ci --legacy-peer-deps
      - name: install Playwright
        run: npx playwright install --with-deps > /dev/null
      - name: run features
        run: npm run test
      - name: Deploy HTML Report to GitHub Pages
        run: |
          npm install -g gh-pages
          gh-pages -d ./reports/cucumber_report.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}